server:
  port: 8113
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/neko_web?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: tiao
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      maxFileSize : 200MB
      maxRequestSize: 200MB


mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
#  type-aliases-package: com.neko.neko.Dao

autoconfigure:
  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
